##Permite criar e gerenciar clusters Kind (Kubernetes IN Docker).
#É usado no recurso kind_cluster para subir um cluster local de testes.
#Não possui parâmetros obrigatórios, pois as configurações vêm do próprio recurso.

##Allows you to create and manage Kind clusters (Kubernetes in Docker).
#It is used in the kind_cluster resource to create a local test cluster.
#It has no mandatory parameters, as the configurations come from the resource itself.
provider "kind" {}

##Conecta o OpenTofu diretamente ao cluster Kubernetes criado.
#Usa o kubeconfig_path gerado pelo recurso kind_cluster para autenticação.
#Permite criar recursos como:
#Namespaces
#Deployments
#Services
#ConfigMaps, etc.

##Connects OpenTofu directly to the newly created Kubernetes cluster.
#Uses the kubeconfig_path generated by the kind_cluster resource for authentication.
#Allows you to create resources such as:
#Namespaces
#Deployments
#Services
#ConfigMaps, etc.
provider "kubernetes" {
  config_path = kind_cluster.default.kubeconfig_path
}

##Permite instalar e gerenciar pacotes Helm dentro do cluster.
#O config_path aponta para o mesmo kubeconfig, garantindo que o Helm se conecte ao cluster recém-criado.
#Usado para instalar aplicações como Grafana, Prometheus, Jenkins.

##Allows you to install and manage Helm packages within the cluster.
#The config_path points to the same kubeconfig, ensuring that Helm connects to the newly created cluster.
#Used to install applications such as Grafana, Prometheus, and Jenkins.
provider "helm" {
  kubernetes {
    config_path = kind_cluster.default.kubeconfig_path
  }
}
